======================= Schemathesis test session starts =======================
Schema location: file:///mnt/d/ag/github/lazarus_target_apis/data/api_petstore/api_petstore.json
Base URL: https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0
Specification version: Open API 3.0.0
Random seed: 337713407196123867417701656586207522321
Workers: 1
Collected API operations: 20
Collected API links: 0
API probing: ...API probing: SUCCESS
Schema analysis: ...Schema analysis: SKIP

POST /AAYUSHGARGBU/api_petstore/1.0.0/pet E                               [  5%]
PUT /AAYUSHGARGBU/api_petstore/1.0.0/pet F                                [ 10%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/pet/findByStatus F                   [ 15%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/pet/findByTags F                     [ 20%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId} F                        [ 25%]
POST /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId} F                       [ 30%]
DELETE /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId} F                     [ 35%]
POST /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId}/uploadImage F           [ 40%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/store/inventory F                    [ 45%]
POST /AAYUSHGARGBU/api_petstore/1.0.0/store/order F                       [ 50%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/store/order/{orderId} F              [ 55%]
DELETE /AAYUSHGARGBU/api_petstore/1.0.0/store/order/{orderId} F           [ 60%]
POST /AAYUSHGARGBU/api_petstore/1.0.0/user F                              [ 65%]
POST /AAYUSHGARGBU/api_petstore/1.0.0/user/createWithArray .              [ 70%]
POST /AAYUSHGARGBU/api_petstore/1.0.0/user/createWithList .               [ 75%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/user/login F                         [ 80%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/user/logout .                        [ 85%]
GET /AAYUSHGARGBU/api_petstore/1.0.0/user/{username} F                    [ 90%]
PUT /AAYUSHGARGBU/api_petstore/1.0.0/user/{username} F                    [ 95%]
DELETE /AAYUSHGARGBU/api_petstore/1.0.0/user/{username} F                 [100%]

==================================== ERRORS ====================================
__________________ POST /AAYUSHGARGBU/api_petstore/1.0.0/pet ___________________
Runtime Error

'latin-1' codec can't encode character '\u0100' in position 0: Body ('Ā') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 816, in network_test
        response = _network_test(case, *args)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 848, in _network_test
        response = case.call(**kwargs)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/models.py", line 310, in call
        response = self.operation.schema.transport.send(
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/transports/__init__.py", line 143, in send
        response = session.request(**data)  # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
        httplib_response = self._make_request(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib/python3.8/http/client.py", line 1256, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
        body = _encode(body, 'body')
      File "/usr/lib/python3.8/http/client.py", line 164, in _encode
        raise UnicodeEncodeError(
    UnicodeEncodeError: 'latin-1' codec can't encode character '\u0100' in position 0: Body ('Ā') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

Runtime Error

'latin-1' codec can't encode characters in position 1-2: Body ('\U00040fbe\U00053fc) is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 816, in network_test
        response = _network_test(case, *args)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 848, in _network_test
        response = case.call(**kwargs)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/models.py", line 310, in call
        response = self.operation.schema.transport.send(
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/transports/__init__.py", line 143, in send
        response = session.request(**data)  # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
        httplib_response = self._make_request(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib/python3.8/http/client.py", line 1256, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
        body = _encode(body, 'body')
      File "/usr/lib/python3.8/http/client.py", line 164, in _encode
        raise UnicodeEncodeError(
    UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1-2: Body ('\U00040fbe\U00053fc) is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

Runtime Error

'latin-1' codec can't encode character '\U0004e103' in position 0: Body ('\U0004e103') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 816, in network_test
        response = _network_test(case, *args)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 848, in _network_test
        response = case.call(**kwargs)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/models.py", line 310, in call
        response = self.operation.schema.transport.send(
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/transports/__init__.py", line 143, in send
        response = session.request(**data)  # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
        httplib_response = self._make_request(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib/python3.8/http/client.py", line 1256, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
        body = _encode(body, 'body')
      File "/usr/lib/python3.8/http/client.py", line 164, in _encode
        raise UnicodeEncodeError(
    UnicodeEncodeError: 'latin-1' codec can't encode character '\U0004e103' in position 0: Body ('\U0004e103') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

Runtime Error

'latin-1' codec can't encode character '\U00053fca' in position 6: Body ('\U00053fca') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 816, in network_test
        response = _network_test(case, *args)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/runner/impl/core.py", line 848, in _network_test
        response = case.call(**kwargs)
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/models.py", line 310, in call
        response = self.operation.schema.transport.send(
      File "/usr/local/lib/python3.8/dist-packages/schemathesis/transports/__init__.py", line 143, in send
        response = session.request(**data)  # type: ignore
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
        resp = conn.urlopen(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
        httplib_response = self._make_request(
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib/python3.8/http/client.py", line 1256, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
        body = _encode(body, 'body')
      File "/usr/lib/python3.8/http/client.py", line 164, in _encode
        raise UnicodeEncodeError(
    UnicodeEncodeError: 'latin-1' codec can't encode character '\U00053fca' in position 6: Body ('\U00053fca') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

Need more help?
    Join our Discord server: https://discord.gg/R9ASRAmHnA
=================================== FAILURES ===================================
__________________ POST /AAYUSHGARGBU/api_petstore/1.0.0/pet ___________________
1. Test Case ID: biDWCo

- Undocumented HTTP status code

    Received: 429
    Documented: 405

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X POST -H 'Content-Type: application/json' -d '{"name": "", "photoUrls": []}' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet

___________________ PUT /AAYUSHGARGBU/api_petstore/1.0.0/pet ___________________
1. Test Case ID: oANMp8

- Undocumented HTTP status code

    Received: 429
    Documented: 400, 404, 405

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X PUT -H 'Content-Type: application/json' -d '{"name": "doggie", "photoUrls": []}' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet

____________ GET /AAYUSHGARGBU/api_petstore/1.0.0/pet/findByStatus _____________
1. Test Case ID: pXQssJ

- Undocumented HTTP status code

    Received: 429
    Documented: 200, 400

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X GET https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet/findByStatus

_____________ GET /AAYUSHGARGBU/api_petstore/1.0.0/pet/findByTags ______________
1. Test Case ID: jLvgom

- Undocumented HTTP status code

    Received: 429
    Documented: 200, 400

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X GET https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet/findByTags

_______________ GET /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId} _______________
1. Test Case ID: J4BDOh

- Undocumented HTTP status code

    Received: 429
    Documented: 200, 400, 404

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X GET -H 'api_key: [Filtered]' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet/0

______________ POST /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId} _______________
1. Test Case ID: z7YIz8

- Undocumented HTTP status code

    Received: 429
    Documented: 405

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet/0

_____________ DELETE /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId} ______________
1. Test Case ID: 1ZIxzw

- Undocumented HTTP status code

    Received: 429
    Documented: 400, 404

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X DELETE https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet/0

________ POST /AAYUSHGARGBU/api_petstore/1.0.0/pet/{petId}/uploadImage _________
1. Test Case ID: 2jl3jB

- Undocumented HTTP status code

    Received: 429
    Documented: 200

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X POST -H 'Content-Type: application/octet-stream' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/pet/0/uploadImage

_____________ GET /AAYUSHGARGBU/api_petstore/1.0.0/store/inventory _____________
[FLAKY] Schemathesis was not able to reliably reproduce this failure

1. Test Case ID: yfeyYU

- Undocumented HTTP status code

    Received: 400
    Documented: 200

[400] Bad Request:

    `<h1>Bad Message 400</h1><pre>reason: Illegal character CNTL=0x1</pre>`

Reproduce with: 

    curl -X GET -H 'api_key: [Filtered]' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/store/inventory

______________ POST /AAYUSHGARGBU/api_petstore/1.0.0/store/order _______________
[FLAKY] Schemathesis was not able to reliably reproduce this failure

1. Test Case ID: 4cIh4x

- Undocumented HTTP status code

    Received: 429
    Documented: 200, 400

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X POST -H 'Content-Type: application/json' -d '{"shipDate": "6840-06-20T16:39:07.457867-05:17"}' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/store/order

__________ GET /AAYUSHGARGBU/api_petstore/1.0.0/store/order/{orderId} __________
1. Test Case ID: dGdVV6

- Undocumented HTTP status code

    Received: 429
    Documented: 200, 400, 404

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X GET https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/store/order/3

________ DELETE /AAYUSHGARGBU/api_petstore/1.0.0/store/order/{orderId} _________
1. Test Case ID: DCysNX

- Undocumented HTTP status code

    Received: 429
    Documented: 400, 404

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X DELETE https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/store/order/1

__________________ POST /AAYUSHGARGBU/api_petstore/1.0.0/user __________________
[FLAKY] Schemathesis was not able to reliably reproduce this failure

1. Test Case ID: kAza0H

- Response timeout

    The server failed to respond within the specified limit of 10000.00ms

Reproduce with: 

    curl -X POST -H 'Content-Type: application/json' -d '{"\u00f0+\b\ud804\udd9c\u00f2\u00a6\udb37\udda3\udb95\udd10": [[-9390306961963760.0, 32029, true], {}], "\u009c\t\udbd2\udfec\uda18\ude02\ud980\ude86\ud817\udd7a\udbbb\udc59": {"": {"": {}, "\ud88e\udf99O\uda0f\udcdc\u00b2\u00edX\u00b2.\u00d0\u00018\u00ef": true, "1\ud9dc\udf02H\n": -45}, "\u00de\u001a\u00bdB,D;": ["4\ud959\udd02\u00f2", ["\u00b4g\ud9e5\udd55\u0083\ud8f2\udcce", [null, "\u00c4\u0087\u00d1b\u00d7", "\u00c9"]], false]}, "\u008e\udba3\udf6d\uc0ee\u00ea\u00d4\\\u008eDS": {"RZHt": {"\f{\u00a0\uda9a\udc72c\u0099\u00d5\u0004\u00f8\u0085\u00bc\u00fc": [], "\u00ab\ud8d1\udfb3\u00d2:\nE\ud93f\udebfOnR\u00fb": true, "\u0094P\ud8a7\ude46\ud9ac\udc8a\u00f0\u00e3E\u0013": "\u00c5X\u00fe"}, "\u00bf\u00bc": [2.5577728658332424e+16], "": []}}' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/user

_______________ GET /AAYUSHGARGBU/api_petstore/1.0.0/user/login ________________
[FLAKY] Schemathesis was not able to reliably reproduce this failure

1. Test Case ID: atdLqm

- Undocumented HTTP status code

    Received: 429
    Documented: 200, 400

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X GET 'https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/user/login?password=&username='

_____________ GET /AAYUSHGARGBU/api_petstore/1.0.0/user/{username} _____________
1. Test Case ID: L57ct4

- Undocumented HTTP status code

    Received: 429
    Documented: 200, 400, 404

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X GET https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/user/0

_____________ PUT /AAYUSHGARGBU/api_petstore/1.0.0/user/{username} _____________
1. Test Case ID: uqt9SF

- Undocumented HTTP status code

    Received: 429
    Documented: 400, 404

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X PUT -H 'Content-Type: application/json' -d '{}' https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/user/0

___________ DELETE /AAYUSHGARGBU/api_petstore/1.0.0/user/{username} ____________
1. Test Case ID: 15TGQo

- Undocumented HTTP status code

    Received: 429
    Documented: 400, 404

[429] Too Many Requests:

    `{"error":"Exceeded rate limit"}`

Reproduce with: 

    curl -X DELETE https://virtserver.swaggerhub.com/AAYUSHGARGBU/api_petstore/1.0.0/user/0

=================================== SUMMARY ====================================

Performed checks:
    not_a_server_error                              365 / 365 passed          PASSED 
    status_code_conformance                         262 / 365 passed          FAILED 
    content_type_conformance                        365 / 365 passed          PASSED 
    response_headers_conformance                    365 / 365 passed          PASSED 
    response_schema_conformance                     365 / 365 passed          PASSED 
    request_timeout                                 0 / 1 passed              FAILED 

Note: Use the 'X-Schemathesis-TestCaseId' header to correlate test case ids from failure messages with server logs for debugging.

Note: To replicate these test failures, rerun with `--hypothesis-seed=337713407196123867417701656586207522321`

Tip: Use the `--report` CLI option to visualize test results via Schemathesis.io.
We run additional conformance checks on reports from public repos.

================== 3 passed, 17 failed, 1 errored in 136.62s ===================
